
name: Live test

on:
  push:
    branches:
      - master

jobs:
  update_test_repo:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Update test repository code
      run: |
        git clone https://FriendsOfGalaxyTester:${{ secrets.TEST_REPO_TOKEN }}@github.com/FriendsOfGalaxyTester/test-integration.git
        cd test-integration
        git config --local user.email "FriendsOfGalaxy+1@gmail.com"
        git config --local user.name "FriendsOfGalaxyTester"
        python autoincrement.py
        git commit -a -m "autoincrement"
        git push origin master

    - name: Trigger sync event on test repo fork
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
      run: |
        curl POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: "application/vnd.github.everest-preview+json, application/vnd.github.v3+json"  \
          https://api.github.com/repos/FriendsOfGalaxy/test-integration-fork/dispatches
          --data '{"event_type": "sync"}'
