name: Update templates

on:
  repository_dispatch:
  push:
    branches:
    - master
    paths:
    - 'templates/**'

jobs:
  update_templates:
    if: (github.event_name == 'push') || (github.event_name == 'repository_dispatch' && github.event.action == 'update_templates')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update templates
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        python -m pip install -r requirements.txt
        python update_templates.py