name: Update templates

on:
  push:
    branches:
    - master
    paths:
    - 'templates/.github/workflows/*.yml'

jobs:
  update_templates:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run update_forks.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python update_workflows.py